<a href="https://colab.research.google.com/github/mandadih/BDA-ICP/blob/main/ICP3A_700772591.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Numpy

In [ ]:
a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row b

In [1]:

import numpy as np

# 1️⃣ Create random vector of size 15 with integers in range 1-20
arr = np.random.randint(1, 21, size=15)
print("Original Array:", arr)

# 2️⃣ Reshape to 3 x 5
arr = arr.reshape(3, 5)
print("\nReshaped Array (3x5):\n", arr)

# 3️⃣ Print array shape
print("\nArray Shape:", arr.shape)

# 4️⃣ Replace max in each row with 0
# Find max in each row and replace it
for i in range(arr.shape[0]):
    row_max = arr[i].max()
    arr[i][arr[i] == row_max] = 0

print("\nArray after replacing max in each row by 0:\n", arr)


Original Array: [ 4 18 17 20  6 13 12  6  3 19  7  5 11  1 16]

Reshaped Array (3x5):
 [[ 4 18 17 20  6]
 [13 12  6  3 19]
 [ 7  5 11  1 16]]

Array Shape: (3, 5)

Array after replacing max in each row by 0:
 [[ 4 18 17  0  6]
 [13 12  6  3  0]
 [ 7  5 11  1  0]]


b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [2]:
import numpy as np

# 1️⃣ Create a 2D array of size 4 x 3 with 4-byte integers (int32)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# 2️⃣ Print the array
print("Array:\n", arr)

# 3️⃣ Print shape
print("\nShape:", arr.shape)

# 4️⃣ Print type
print("Type:", type(arr))

# 5️⃣ Print data type
print("Data type of elements:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type of elements: int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [3]:
import numpy as np

# 1️⃣ Given square array
A = np.array([[3, -2],
              [1,  0]])

print("Given Array:\n", A)

# 2️⃣ Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# 3️⃣ Print results
print("\nEigenvalues:", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Given Array:
 [[ 3 -2]
 [ 1  0]]

Eigenvalues: [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [4]:
import numpy as np

# 1️⃣ Given array
A = np.array([[0, 1, 2],
              [3, 4, 5]])

print("Given Array:\n", A)

# 2️⃣ Compute sum of diagonal elements
diag_sum = np.trace(A)

# 3️⃣ Print result
print("\nSum of diagonal elements:", diag_sum)


Given Array:
 [[0 1 2]
 [3 4 5]]

Sum of diagonal elements: 4


e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [5]:
import numpy as np

# 1️⃣ Original 3x2 array
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Original Array (3x2):\n", A)

# 2️⃣ Reshape to 2x3
A_reshaped = A.reshape(2, 3)

# 3️⃣ Print reshaped array
print("\nReshaped Array (2x3):\n", A_reshaped)


Original Array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
